
package com.ibm.insurance.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductDetailsService", targetNamespace = "http://product.insurance.ibm.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductDetailsService {


    /**
     * 
     * @param productRequest
     * @return
     *     returns com.ibm.insurance.stubs.ProductResponse
     */
    @WebMethod(operationName = "Product")
    @WebResult(name = "ProductResponse", targetNamespace = "http://product.insurance.ibm.com", partName = "ProductResponse")
    public ProductResponse product(
        @WebParam(name = "ProductRequest", targetNamespace = "http://product.insurance.ibm.com", partName = "ProductRequest")
        ProductRequest productRequest);

}
