
package com.ibm.insurance.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductDetailsServices", targetNamespace = "http://product.insurance.ibm.com", wsdlLocation = "file:/C:/Users/IBM_ADMIN/IBM/rationalsdp/workspace/MetLifeProducts/src/main/webapp/WEB-INF/wsdl/ProductDetailsService.wsdl")
public class ProductDetailsServices
    extends Service
{

    private final static URL PRODUCTDETAILSSERVICES_WSDL_LOCATION;
    private final static WebServiceException PRODUCTDETAILSSERVICES_EXCEPTION;
    private final static QName PRODUCTDETAILSSERVICES_QNAME = new QName("http://product.insurance.ibm.com", "ProductDetailsServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/IBM_ADMIN/IBM/rationalsdp/workspace/MetLifeProducts/src/main/webapp/WEB-INF/wsdl/ProductDetailsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTDETAILSSERVICES_WSDL_LOCATION = url;
        PRODUCTDETAILSSERVICES_EXCEPTION = e;
    }

    public ProductDetailsServices() {
        super(__getWsdlLocation(), PRODUCTDETAILSSERVICES_QNAME);
    }

    public ProductDetailsServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTDETAILSSERVICES_QNAME, features);
    }

    public ProductDetailsServices(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTDETAILSSERVICES_QNAME);
    }

    public ProductDetailsServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTDETAILSSERVICES_QNAME, features);
    }

    public ProductDetailsServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductDetailsServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductDetailsService
     */
    @WebEndpoint(name = "ProductDetailsServiceSoap11")
    public ProductDetailsService getProductDetailsServiceSoap11() {
        return super.getPort(new QName("http://product.insurance.ibm.com", "ProductDetailsServiceSoap11"), ProductDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductDetailsService
     */
    @WebEndpoint(name = "ProductDetailsServiceSoap11")
    public ProductDetailsService getProductDetailsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://product.insurance.ibm.com", "ProductDetailsServiceSoap11"), ProductDetailsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTDETAILSSERVICES_EXCEPTION!= null) {
            throw PRODUCTDETAILSSERVICES_EXCEPTION;
        }
        return PRODUCTDETAILSSERVICES_WSDL_LOCATION;
    }

}
