//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.30 at 11:16:47 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://org/ibm/claims/webservices/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ibm.webservice.stubs;
